version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    use_colors: true
  access:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    use_colors: true

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  groove_api:
    level: INFO
    handlers: [default]
    propagate: no
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [access]
    propagate: no

root:
  level: INFO
  handlers: [default]